# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportShard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_model_path', models.CharField(editable=False, max_length=500)),
                ('task_id', models.PositiveIntegerField()),
                ('source_data_json', models.TextField()),
                ('last_row_processed', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('start_line_number', models.PositiveIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('error_csv_filename', models.CharField(max_length=1023)),
                ('error_csv_written', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportShardError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmosis.ImportShard')),
            ],
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(editable=False, max_length=500)),
                ('source_data', models.FileField(max_length=1023, upload_to=b'', verbose_name=b'File')),
                ('error_csv', models.FileField(editable=False, max_length=1023, null=True, upload_to=b'', verbose_name=b'Error File')),
                ('error_csv_filename', models.CharField(editable=False, max_length=1023)),
                ('row_count', models.PositiveIntegerField(default=0, editable=False)),
                ('shard_count', models.PositiveIntegerField(default=0, editable=False)),
                ('shards_processed', models.PositiveIntegerField(default=0, editable=False)),
                ('shards_error_csv_written', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'in_progress', b'In Progress'), (b'finished', b'Finished')], default=b'pending', editable=False, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
